Resources:
    todoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todo-db-prod
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: dateCreated
            AttributeType: N
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: dateCreated
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1